import { Language } from './types';

export const formatCurrency = (value: number): string => {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
};

export const TRANSLATIONS = {
  EN: {
    dashboard: {
      totalBalance: 'Total Balance',
      netWorth: 'Net Worth',
      monthlyIncome: 'Mthly Income',
      monthlyExpense: 'Mthly Expense',
      active: 'Active',
      for: 'For',
      includes: 'Includes Assets & Debts',
      expenseBreakdown: 'Expense Breakdown',
      assetGrowth: 'Asset Growth'
    },
    transactions: {
      title: 'Transactions',
      subtitle: 'Manage & Track Your Cashflow',
      new: 'New Transaction',
      totalIncome: 'Total Income',
      totalExpense: 'Total Expense',
      netBalance: 'Net Balance',
      searchPlaceholder: 'Search by description or category...',
      date: 'Date',
      category: 'Category',
      description: 'Description',
      user: 'User',
      amount: 'Amount',
      save: 'Save Record',
      cancel: 'Cancel',
      type: 'Type',
      expense: 'Expense',
      income: 'Income',
      transfer: 'Transfer',
      details: 'Transaction Details',
      edit: 'Edit',
      delete: 'Delete',
      confirmDelete: 'Are you sure you want to delete this transaction? The asset balance will be reverted.',
      update: 'Update Transaction',
      sourceAccount: 'Source Account',
      selectAccount: 'Select Asset/Wallet',
      insufficient: 'Insufficient funds in selected account!',
      history: 'Edit History',
      editedBy: 'Edited by',
      originalAmount: 'Prev Amount'
    },
    kanban: {
      todo: 'To Pay',
      planned: 'Planned',
      paid: 'Paid',
      overdue: 'Overdue',
      empty: 'Empty'
    },
    savings: {
      title: 'Savings Goals',
      subtitle: 'Dream big, save bigger.',
      new: 'New Goal',
      target: 'Target',
      deadline: 'Deadline',
      progress: 'Progress',
      addMoney: 'Add Money',
      create: 'Create Goal',
      name: 'Goal Name',
      amount: 'Target Amount',
      icon: 'Icon',
      history: 'Contribution History',
      noHistory: 'No contributions yet.',
      goalReached: 'Goal Reached!',
      details: 'Goal Details',
      remaining: 'Remaining'
    },
    debt: {
      title: 'Debt Manager',
      subtitle: 'Kill your debt before it kills you.',
      add: 'Add Record',
      owe: 'I Owe (Hutang)',
      owed: 'Owed to Me (Piutang)',
      lender: 'Lender',
      borrower: 'Borrower',
      due: 'Due',
      repayment: 'Repayment',
      collected: 'Collected',
      payNow: 'Pay / Installment',
      markPaid: 'Receive Payment',
      history: 'History',
      remind: 'Remind',
      recordName: 'Record Name',
      person: 'Person / Entity',
      paymentDate: 'Payment Date',
      receiveAccount: 'Deposit To',
      payFrom: 'Pay From'
    },
    budget: {
      title: 'Budgeting',
      subtitle: 'Control your spending habits.',
      edit: 'Edit Budgets',
      vs: 'Budget vs Actual',
      breakdown: 'Category Breakdown',
      over: 'OVER BUDGET',
      quick: 'Quick Add',
      set: 'Set Budget',
      limit: 'Spending Limit',
      period: 'Period',
      monthly: 'Monthly',
      weekly: 'Weekly'
    },
    assets: {
      title: 'Assets & Liabilities',
      subtitle: 'Your net worth breakdown.',
      add: 'Add Asset',
      cash: 'Cash / Bank',
      investment: 'Investment',
      property: 'Property',
      debt: 'Debt (Liability)',
      save: 'Save Asset',
      name: 'Asset Name',
      value: 'Value',
      addNew: 'Add New Asset',
      runningBalance: 'Running Balance'
    },
    ai: {
      title: 'AI Assistant',
      autoRecord: 'AI Auto-Record',
      desc: 'Type normally like "Spent 50k on Taxi" or "Salary 5000 incoming". Gemini will extract the data automatically.',
      record: 'Record',
      insights: 'Insights',
      placeholder: 'e.g. Paid internet bill 450000...',
      process: 'Process Entry',
      processing: 'Processing...',
      genInsights: 'Generate Insights',
      recent: 'Recent Activity',
      analyzePrompt: 'Analyze your last 10 transactions for patterns.'
    },
    settings: {
      title: 'Settings',
      subtitle: 'Customize your experience.',
      tabs: {
        profile: 'Profile',
        categories: 'Categories',
        team: 'Team',
        system: 'System'
      },
      profile: {
        user: 'User Profile',
        displayName: 'Display Name',
        theme: 'Theme Color',
        save: 'Save Changes'
      },
      categories: {
        expense: 'Expense Categories',
        income: 'Income Categories',
        expenseTags: 'Outgoing Money Tags',
        incomeTags: 'Incoming Money Tags',
        add: 'Add',
        newExp: 'New Expense Tag...',
        newInc: 'New Income Tag...'
      },
      team: {
        title: 'Collaborators',
        invite: 'Invite Friend',
        desc: 'Manage who can access and add transactions.',
        name: 'Name',
        role: 'Role',
        addUser: 'Add User',
        newUserName: 'Friend Name',
        color: 'Avatar Color'
      },
      system: {
        data: 'Data Management',
        control: 'Control your local data.',
        export: 'Export Data (JSON)',
        reset: 'Reset All Data',
        about: 'About'
      }
    }
  },
  ID: {
    dashboard: {
      totalBalance: 'Total Saldo',
      netWorth: 'Kekayaan Bersih',
      monthlyIncome: 'Pemasukan Bln',
      monthlyExpense: 'Pengeluaran Bln',
      active: 'Aktif',
      for: 'Untuk',
      includes: 'Termasuk Aset & Hutang',
      expenseBreakdown: 'Rincian Pengeluaran',
      assetGrowth: 'Pertumbuhan Aset'
    },
    transactions: {
      title: 'Transaksi',
      subtitle: 'Kelola & Pantau Arus Kas',
      new: 'Transaksi Baru',
      totalIncome: 'Total Pemasukan',
      totalExpense: 'Total Pengeluaran',
      netBalance: 'Saldo Bersih',
      searchPlaceholder: 'Cari deskripsi atau kategori...',
      date: 'Tanggal',
      category: 'Kategori',
      description: 'Deskripsi',
      user: 'User',
      amount: 'Jumlah',
      save: 'Simpan',
      cancel: 'Batal',
      type: 'Tipe',
      expense: 'Pengeluaran',
      income: 'Pemasukan',
      transfer: 'Transfer',
      details: 'Detail Transaksi',
      edit: 'Ubah',
      delete: 'Hapus',
      confirmDelete: 'Apakah Anda yakin ingin menghapus transaksi ini? Saldo aset akan dikembalikan.',
      update: 'Perbarui Transaksi',
      sourceAccount: 'Sumber Dana / Akun',
      selectAccount: 'Pilih Aset/Dompet',
      insufficient: 'Saldo tidak cukup di akun yang dipilih!',
      history: 'Riwayat Perubahan',
      editedBy: 'Diubah oleh',
      originalAmount: 'Jumlah Awal'
    },
    kanban: {
      todo: 'Harus Bayar',
      planned: 'Terencana',
      paid: 'Lunas',
      overdue: 'Telat',
      empty: 'Kosong'
    },
    savings: {
      title: 'Target Tabungan',
      subtitle: 'Mimpi besar, nabung lebih besar.',
      new: 'Target Baru',
      target: 'Target',
      deadline: 'Tenggat',
      progress: 'Progres',
      addMoney: 'Tambah Saldo',
      create: 'Buat Target',
      name: 'Nama Target',
      amount: 'Jumlah Target',
      icon: 'Ikon',
      history: 'Riwayat Menabung',
      noHistory: 'Belum ada riwayat menabung.',
      goalReached: 'Target Tercapai!',
      details: 'Detail Target',
      remaining: 'Sisa'
    },
    debt: {
      title: 'Manajemen Hutang',
      subtitle: 'Lunasi hutang sebelum menumpuk.',
      add: 'Tambah Catatan',
      owe: 'Hutang Saya',
      owed: 'Piutang (Orang Hutang)',
      lender: 'Pemberi Pinjaman',
      borrower: 'Peminjam',
      due: 'Jatuh Tempo',
      repayment: 'Pembayaran',
      collected: 'Terkumpul',
      payNow: 'Bayar / Cicil',
      markPaid: 'Terima Pembayaran',
      history: 'Riwayat',
      remind: 'Ingatkan',
      recordName: 'Nama Catatan',
      person: 'Orang / Entitas',
      paymentDate: 'Tanggal Bayar',
      receiveAccount: 'Masuk ke Akun',
      payFrom: 'Bayar dari Akun'
    },
    budget: {
      title: 'Anggaran (Budget)',
      subtitle: 'Kontrol kebiasaan belanja.',
      edit: 'Edit Anggaran',
      vs: 'Anggaran vs Aktual',
      breakdown: 'Rincian Kategori',
      over: 'OVER BUDGET',
      quick: 'Tambah Cepat',
      set: 'Set Anggaran',
      limit: 'Batas Belanja',
      period: 'Periode',
      monthly: 'Bulanan',
      weekly: 'Mingguan'
    },
    assets: {
      title: 'Aset & Kewajiban',
      subtitle: 'Rincian kekayaan bersih.',
      add: 'Tambah Aset',
      cash: 'Kas / Bank',
      investment: 'Investasi',
      property: 'Properti',
      debt: 'Hutang (Kewajiban)',
      save: 'Simpan Aset',
      name: 'Nama Aset',
      value: 'Nilai',
      addNew: 'Tambah Aset Baru',
      runningBalance: 'Saldo Berjalan'
    },
    ai: {
      title: 'Asisten AI',
      autoRecord: 'Catat Otomatis AI',
      desc: 'Ketik biasa seperti "Abis 50rb buat bensin" atau "Gaji masuk 5 juta". Gemini akan mencatat datanya.',
      record: 'Rekam',
      insights: 'Analisa',
      placeholder: 'Contoh: Bayar tagihan internet 450000...',
      process: 'Proses Data',
      processing: 'Memproses...',
      genInsights: 'Buat Analisa',
      recent: 'Aktivitas Terkini',
      analyzePrompt: 'Analisa 10 transaksi terakhir untuk pola keuangan.'
    },
    settings: {
      title: 'Pengaturan',
      subtitle: 'Sesuaikan pengalaman aplikasi.',
      tabs: {
        profile: 'Profil',
        categories: 'Kategori',
        team: 'Tim',
        system: 'Sistem'
      },
      profile: {
        user: 'Profil Pengguna',
        displayName: 'Nama Tampilan',
        theme: 'Warna Tema',
        save: 'Simpan Perubahan'
      },
      categories: {
        expense: 'Kategori Pengeluaran',
        income: 'Kategori Pemasukan',
        expenseTags: 'Label Uang Keluar',
        incomeTags: 'Label Uang Masuk',
        add: 'Tambah',
        newExp: 'Tag Pengeluaran Baru...',
        newInc: 'Tag Pemasukan Baru...'
      },
      team: {
        title: 'Kolaborator',
        invite: 'Undang Teman',
        desc: 'Atur siapa yang bisa mengakses dan mencatat.',
        name: 'Nama',
        role: 'Peran',
        addUser: 'Tambah User',
        newUserName: 'Nama Teman',
        color: 'Warna Avatar'
      },
      system: {
        data: 'Manajemen Data',
        control: 'Kontrol data lokal anda.',
        export: 'Ekspor Data (JSON)',
        reset: 'Reset Semua Data',
        about: 'Tentang'
      }
    }
  }
};
